# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  # Datasource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #spring:jpa:hibernate:ddl-auto=create

  #CONFIGURACOES SPRING BATCH
  batch:
    job:
      enabled: true
    initialize-schema: always

  #DIRETORIOS
file:
  directory:
    out: /tmp/output/
